package com.pineandpackets.pocketlab.engine.archive

import com.pineandpackets.pocketlab.core.common.AnalysisError
import com.pineandpackets.pocketlab.core.common.AnalysisLimits
import com.pineandpackets.pocketlab.engine.apk.ApkAnalyzer
import com.pineandpackets.pocketlab.core.model.ApkInfo
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonPrimitive
import timber.log.Timber
import java.io.File
import java.util.zip.ZipFile

/**
 * Analyzer for APKS and XAPK package formats.
 * 
 * APKS: Generated by bundletool, contains base APK + configuration splits
 * XAPK: Third-party format (APKPure, etc.), contains APKs + metadata
 */
class PackageSetAnalyzer {
    
    private val apkAnalyzer = ApkAnalyzer()
    private val archiveAnalyzer = ArchiveAnalyzer()
    private val json = Json { ignoreUnknownKeys = true }
    
    /**
     * Analyzes an APKS or XAPK package set.
     * 
     * @param packageSetFile The APKS/XAPK file to analyze
     * @return Analysis result with merged information from all contained APKs
     */
    fun analyzePackageSet(packageSetFile: File): Result<PackageSetAnalysisResult> {
        return try {
            // First, determine the type
            val type = detectPackageSetType(packageSetFile)
            if (type == null) {
                return Result.failure(
                    AnalysisError.ArchiveError("Not a valid APKS or XAPK file")
                )
            }
            
            Timber.i("Detected package set type: $type")
            
            // Analyze based on type
            when (type) {
                PackageSetType.APKS -> analyzeApks(packageSetFile)
                PackageSetType.XAPK -> analyzeXapk(packageSetFile)
            }
        } catch (e: Exception) {
            Timber.e(e, "Failed to analyze package set")
            Result.failure(AnalysisError.ArchiveError("Failed to analyze package set", e))
        }
    }
    
    fun detectPackageSetType(file: File): PackageSetType? {
        return try {
            ZipFile(file).use { zip ->
                val entries = zip.entries().asSequence().map { it.name }.toList()
                
                // APKS detection: contains .apk files and optionally BundleConfig.pb
                val hasApks = entries.any { it.endsWith(".apk") }
                val hasBundleConfig = entries.contains("BundleConfig.pb")
                if (hasApks && hasBundleConfig) {
                    return PackageSetType.APKS
                }
                
                // XAPK detection: contains manifest.json and .apk files
                val hasManifest = entries.contains("manifest.json")
                if (hasApks && hasManifest) {
                    return PackageSetType.XAPK
                }
                
                // Fallback: if it has multiple APKs, treat as APKS
                val apkCount = entries.count { it.endsWith(".apk") }
                if (apkCount > 1) {
                    return PackageSetType.APKS
                }
                
                null
            }
        } catch (e: Exception) {
            Timber.w(e, "Failed to detect package set type")
            null
        }
    }
    
    private fun analyzeApks(file: File): Result<PackageSetAnalysisResult> {
        val apkResults = mutableListOf<ApkAnalysisResultEntry>()
        val errors = mutableListOf<String>()
        val warnings = mutableListOf<String>()
        var totalApkCount = 0
        
        ZipFile(file).use { zip ->
            val apkEntries = zip.entries().asSequence()
                .filter { it.name.endsWith(".apk") }
                .toList()
            
            totalApkCount = apkEntries.size
            
            if (apkEntries.isEmpty()) {
                return Result.failure(
                    AnalysisError.ArchiveError("APKS file contains no APK entries")
                )
            }
            
            // Check quota
            if (apkEntries.size > AnalysisLimits.MAX_DEX_COUNT) {
                return Result.failure(
                    AnalysisError.QuotaExceededError(
                        "APKS contains ${apkEntries.size} APKs, exceeds limit of ${AnalysisLimits.MAX_DEX_COUNT}"
                    )
                )
            }
            
            // Extract and analyze each APK
            for (entry in apkEntries) {
                val tempFile = File.createTempFile("apks_entry_", ".apk")
                try {
                    zip.getInputStream(entry).use { input ->
                        tempFile.outputStream().use { output ->
                            input.copyTo(output)
                        }
                    }
                    
                    val apkResult = apkAnalyzer.analyzeApk(tempFile)
                    if (apkResult.isSuccess) {
                        val analysisResult = apkResult.getOrNull()
                        apkResults.add(
                            ApkAnalysisResultEntry(
                                entryName = entry.name,
                                apkInfo = analysisResult?.apkInfo,
                                isBaseApk = entry.name.contains("base", ignoreCase = true)
                            )
                        )
                    } else {
                        val errorMsg = apkResult.exceptionOrNull()?.message ?: "Unknown error"
                        errors.add("Failed to analyze ${entry.name}: $errorMsg")
                        Timber.w("Failed to analyze APK entry ${entry.name}: $errorMsg")
                    }
                } finally {
                    tempFile.delete()
                }
            }
        }
        
        if (apkResults.isEmpty()) {
            // Even if no APKs could be analyzed, we still detected the format
            // Return success with empty results
            return Result.success(
                PackageSetAnalysisResult(
                    type = PackageSetType.APKS,
                    apkCount = totalApkCount,
                    analyzedApkCount = 0,
                    apkResults = emptyList(),
                    mergedApkInfo = null,
                    errors = errors + "No APKs could be successfully analyzed",
                    warnings = warnings
                )
            )
        }
        
        // Merge results
        val merged = mergeApkResults(apkResults, warnings)
        
        return Result.success(
            PackageSetAnalysisResult(
                type = PackageSetType.APKS,
                apkCount = totalApkCount,
                analyzedApkCount = apkResults.size,
                apkResults = apkResults,
                mergedApkInfo = merged,
                errors = errors,
                warnings = warnings
            )
        )
    }
    
    private fun analyzeXapk(file: File): Result<PackageSetAnalysisResult> {
        val apkResults = mutableListOf<ApkAnalysisResultEntry>()
        val errors = mutableListOf<String>()
        val warnings = mutableListOf<String>()
        var manifestInfo: XapkManifestInfo? = null
        var totalApkCount = 0
        
        ZipFile(file).use { zip ->
            // Parse manifest.json if present
            val manifestEntry = zip.getEntry("manifest.json")
            if (manifestEntry != null) {
                try {
                    val manifestJson = zip.getInputStream(manifestEntry).bufferedReader().use { it.readText() }
                    manifestInfo = parseXapkManifest(manifestJson)
                } catch (e: Exception) {
                    warnings.add("Failed to parse XAPK manifest: ${e.message}")
                    Timber.w(e, "Failed to parse XAPK manifest")
                }
            }
            
            // Extract and analyze APKs
            val apkEntries = zip.entries().asSequence()
                .filter { it.name.endsWith(".apk") }
                .toList()
            
            totalApkCount = apkEntries.size
            
            if (apkEntries.isEmpty()) {
                return Result.failure(
                    AnalysisError.ArchiveError("XAPK file contains no APK entries")
                )
            }
            
            // Check quota
            if (apkEntries.size > AnalysisLimits.MAX_DEX_COUNT) {
                return Result.failure(
                    AnalysisError.QuotaExceededError(
                        "XAPK contains ${apkEntries.size} APKs, exceeds limit of ${AnalysisLimits.MAX_DEX_COUNT}"
                    )
                )
            }
            
            for (entry in apkEntries) {
                val tempFile = File.createTempFile("xapk_entry_", ".apk")
                try {
                    zip.getInputStream(entry).use { input ->
                        tempFile.outputStream().use { output ->
                            input.copyTo(output)
                        }
                    }
                    
                    val apkResult = apkAnalyzer.analyzeApk(tempFile)
                    if (apkResult.isSuccess) {
                        val analysisResult = apkResult.getOrNull()
                        apkResults.add(
                            ApkAnalysisResultEntry(
                                entryName = entry.name,
                                apkInfo = analysisResult?.apkInfo,
                                isBaseApk = entry.name.contains("base", ignoreCase = true)
                            )
                        )
                    } else {
                        val errorMsg = apkResult.exceptionOrNull()?.message ?: "Unknown error"
                        errors.add("Failed to analyze ${entry.name}: $errorMsg")
                        Timber.w("Failed to analyze APK entry ${entry.name}: $errorMsg")
                    }
                } finally {
                    tempFile.delete()
                }
            }
        }
        
        if (apkResults.isEmpty()) {
            // Even if no APKs could be analyzed, we still detected the format
            // Return success with empty results
            return Result.success(
                PackageSetAnalysisResult(
                    type = PackageSetType.XAPK,
                    apkCount = totalApkCount,
                    analyzedApkCount = 0,
                    apkResults = emptyList(),
                    mergedApkInfo = null,
                    manifestInfo = manifestInfo,
                    errors = errors + "No APKs could be successfully analyzed",
                    warnings = warnings
                )
            )
        }
        
        // Merge results
        val merged = mergeApkResults(apkResults, warnings)
        
        return Result.success(
            PackageSetAnalysisResult(
                type = PackageSetType.XAPK,
                apkCount = totalApkCount,
                analyzedApkCount = apkResults.size,
                apkResults = apkResults,
                mergedApkInfo = merged,
                manifestInfo = manifestInfo,
                errors = errors,
                warnings = warnings
            )
        )
    }
    
    private fun parseXapkManifest(jsonString: String): XapkManifestInfo {
        val jsonObj = json.parseToJsonElement(jsonString) as JsonObject
        
        return XapkManifestInfo(
            xapkVersion = jsonObj["xapk_version"]?.jsonPrimitive?.content?.toIntOrNull(),
            packageName = jsonObj["package_name"]?.jsonPrimitive?.content,
            versionName = jsonObj["version_name"]?.jsonPrimitive?.content,
            versionCode = jsonObj["version_code"]?.jsonPrimitive?.content?.toLongOrNull()
        )
    }
    
    private fun mergeApkResults(
        results: List<ApkAnalysisResultEntry>,
        warnings: MutableList<String>
    ): ApkInfo? {
        if (results.isEmpty()) return null
        
        // Prefer base APK if available
        val baseApk = results.find { it.isBaseApk }
        val primaryApk = baseApk ?: results.first()
        val primaryInfo = primaryApk.apkInfo ?: return null
        
        // Check for inconsistencies
        val packageNames = results.mapNotNull { it.apkInfo?.packageName }.distinct()
        if (packageNames.size > 1) {
            warnings.add("Inconsistent package names across APKs: ${packageNames.joinToString(", ")}")
        }
        
        val versionCodes = results.mapNotNull { it.apkInfo?.versionCode }.distinct()
        if (versionCodes.size > 1) {
            warnings.add("Inconsistent version codes across APKs: ${versionCodes.joinToString(", ")}")
        }
        
        // Check signing certificate consistency
        val signingCerts = results.mapNotNull { 
            it.apkInfo?.signingInfo?.certificates?.firstOrNull()?.fingerprint 
        }.distinct()
        if (signingCerts.size > 1) {
            warnings.add("Different signing certificates across APKs - this is suspicious")
        }
        
        // Merge permissions (union)
        val allPermissions = results.flatMap { 
            it.apkInfo?.permissions ?: emptyList() 
        }.distinctBy { it.name }
        
        // Merge components (union)
        val allComponents = results.flatMap { 
            it.apkInfo?.components ?: emptyList() 
        }.distinctBy { "${it.type}:${it.name}" }
        
        return primaryInfo.copy(
            permissions = allPermissions,
            components = allComponents
        )
    }
}

enum class PackageSetType {
    APKS,
    XAPK
}

data class PackageSetAnalysisResult(
    val type: PackageSetType,
    val apkCount: Int,
    val analyzedApkCount: Int,
    val apkResults: List<ApkAnalysisResultEntry>,
    val mergedApkInfo: ApkInfo?,
    val manifestInfo: XapkManifestInfo? = null,
    val errors: List<String> = emptyList(),
    val warnings: List<String> = emptyList()
)

data class ApkAnalysisResultEntry(
    val entryName: String,
    val apkInfo: ApkInfo?,
    val isBaseApk: Boolean
)

data class XapkManifestInfo(
    val xapkVersion: Int?,
    val packageName: String?,
    val versionName: String?,
    val versionCode: Long?
)
