package com.pineandpackets.pocketlab.core.report

import com.pineandpackets.pocketlab.core.model.AnalysisReport
import com.pineandpackets.pocketlab.core.model.RedactionSettings

class ReportExporter(
    private val redactor: ReportRedactor = ReportRedactor()
) {

    fun exportToJson(report: AnalysisReport, settings: RedactionSettings = RedactionSettings()): String {
        val sanitizedReport = redactor.redact(report, settings)
        val serializer = ReportSerializer()
        return serializer.serialize(sanitizedReport)
    }

    fun exportToMarkdown(report: AnalysisReport, settings: RedactionSettings = RedactionSettings()): String {
        val sanitizedReport = redactor.redact(report, settings)
        val sb = StringBuilder()

        sb.appendLine("# Analysis Report")
        sb.appendLine()
        sb.appendLine("**Report ID:** ${sanitizedReport.reportId}")
        sb.appendLine("**Case ID:** ${sanitizedReport.caseId}")
        sb.appendLine("**Created:** ${sanitizedReport.createdAt}")
        sb.appendLine()

        sb.appendLine("## Summary")
        sb.appendLine()
        sb.appendLine("- **Risk Band:** ${sanitizedReport.summary.riskBand}")
        sb.appendLine("- **Confidence:** ${sanitizedReport.summary.confidence}")
        sb.appendLine("- **Completeness:** ${"%.0f".format(sanitizedReport.summary.completeness * 100)}%")
        sb.appendLine("- **Finding Count:** ${sanitizedReport.summary.findingCount}")
        sb.appendLine()

        sb.appendLine("## Source")
        sb.appendLine()
        sb.appendLine("- **Display Name:** ${escapeMarkdown(sanitizedReport.source.displayName)}")
        sb.appendLine("- **SHA-256:** `${sanitizedReport.source.sha256}`")
        sb.appendLine()

        if (sanitizedReport.findings.isNotEmpty()) {
            sb.appendLine("## Findings")
            sb.appendLine()
            sanitizedReport.findings.forEach { finding ->
                sb.appendLine("### ${finding.title}")
                sb.appendLine()
                sb.appendLine("- **Severity:** ${finding.severity}")
                sb.appendLine("- **Confidence:** ${finding.confidence}")
                sb.appendLine("- **Category:** ${finding.category}")
                sb.appendLine()
                sb.appendLine("**Simple Explanation:**")
                sb.appendLine(finding.simpleExplanation)
                sb.appendLine()
                sb.appendLine("**Analyst Explanation:**")
                sb.appendLine(finding.analystExplanation)
                sb.appendLine()

                if (finding.limitations.isNotEmpty()) {
                    sb.appendLine("**Limitations:**")
                    finding.limitations.forEach { sb.appendLine("- $it") }
                    sb.appendLine()
                }

                if (finding.recommendations.isNotEmpty()) {
                    sb.appendLine("**Recommendations:**")
                    finding.recommendations.forEach { sb.appendLine("- $it") }
                    sb.appendLine()
                }
            }
        }

        if (sanitizedReport.limitations.isNotEmpty()) {
            sb.appendLine("## Report Limitations")
            sb.appendLine()
            sanitizedReport.limitations.forEach { sb.appendLine("- $it") }
            sb.appendLine()
        }

        sb.appendLine("---")
        sb.appendLine()
        sb.appendLine("*Generated by PocketLab v${sanitizedReport.engine.appVersion}*")

        return sb.toString()
    }

    fun exportToHtml(report: AnalysisReport, settings: RedactionSettings = RedactionSettings()): String {
        val sanitizedReport = redactor.redact(report, settings)
        val sb = StringBuilder()

        sb.appendLine("<!DOCTYPE html>")
        sb.appendLine("<html lang=\"en\">")
        sb.appendLine("<head>")
        sb.appendLine("  <meta charset=\"UTF-8\">")
        sb.appendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
        sb.appendLine("  <title>Analysis Report</title>")
        sb.appendLine("  <style>")
        sb.appendLine("    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }")
        sb.appendLine("    h1 { color: #333; }")
        sb.appendLine("    .finding { border: 1px solid #ddd; padding: 15px; margin: 15px 0; border-radius: 5px; }")
        sb.appendLine("    .severity { font-weight: bold; }")
        sb.appendLine("    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }")
        sb.appendLine("    .limitations { color: #666; font-style: italic; }")
        sb.appendLine("  </style>")
        sb.appendLine("</head>")
        sb.appendLine("<body>")

        sb.appendLine("  <h1>Analysis Report</h1>")
        sb.appendLine("  <p><strong>Report ID:</strong> ${escapeHtml(sanitizedReport.reportId)}</p>")
        sb.appendLine("  <p><strong>Case ID:</strong> ${escapeHtml(sanitizedReport.caseId)}</p>")
        sb.appendLine("  <p><strong>Created:</strong> ${escapeHtml(sanitizedReport.createdAt)}</p>")
        sb.appendLine("  <p><strong>Source:</strong> ${escapeHtml(sanitizedReport.source.displayName)}</p>")

        sb.appendLine("  <h2>Summary</h2>")
        sb.appendLine("  <ul>")
        sb.appendLine("    <li><strong>Risk Band:</strong> ${escapeHtml(sanitizedReport.summary.riskBand.name)}</li>")
        sb.appendLine("    <li><strong>Confidence:</strong> ${escapeHtml(sanitizedReport.summary.confidence.name)}</li>")
        sb.appendLine("    <li><strong>Completeness:</strong> ${"%.0f".format(sanitizedReport.summary.completeness * 100)}%</li>")
        sb.appendLine("  </ul>")

        if (sanitizedReport.findings.isNotEmpty()) {
            sb.appendLine("  <h2>Findings</h2>")
            sanitizedReport.findings.forEach { finding ->
                sb.appendLine("  <div class=\"finding\">")
                sb.appendLine("    <h3>${escapeHtml(finding.title)}</h3>")
                sb.appendLine("    <p class=\"severity\">Severity: ${escapeHtml(finding.severity.name)}</p>")
                sb.appendLine("    <p>${escapeHtml(finding.simpleExplanation)}</p>")
                sb.appendLine("  </div>")
            }
        }

        if (sanitizedReport.limitations.isNotEmpty()) {
            sb.appendLine("  <h2>Report Limitations</h2>")
            sb.appendLine("  <ul class=\"limitations\">")
            sanitizedReport.limitations.forEach { limitation ->
                sb.appendLine("    <li>${escapeHtml(limitation)}</li>")
            }
            sb.appendLine("  </ul>")
        }

        sb.appendLine("  <hr>")
        sb.appendLine("  <p><em>Generated by PocketLab v${escapeHtml(sanitizedReport.engine.appVersion)}</em></p>")
        sb.appendLine("</body>")
        sb.appendLine("</html>")

        return sb.toString()
    }

    fun exportIocsToCsv(report: AnalysisReport, settings: RedactionSettings = RedactionSettings()): String {
        val sanitizedReport = redactor.redact(report, settings)
        val sb = StringBuilder()

        sb.appendLine("type,value,defanged_value,confidence,context,file,entry,class,method,offset")

        sanitizedReport.indicators.forEach { indicator ->
            val type = escapeCsv(indicator.type.name)
            val displayValue = escapeCsv(indicator.displayValue)
            val defangedValue = escapeCsv(indicator.defangedValue)
            val confidence = escapeCsv(indicator.confidence.name)
            val context = escapeCsv(indicator.context ?: "")

            val file = escapeCsv(indicator.source?.container ?: "")
            val entry = escapeCsv(indicator.source?.entry ?: "")
            val className = escapeCsv(indicator.source?.className ?: "")
            val method = escapeCsv(indicator.source?.method ?: "")
            val offset = indicator.source?.offset?.toString() ?: ""

            sb.appendLine("$type,$displayValue,$defangedValue,$confidence,$context,$file,$entry,$className,$method,$offset")
        }

        return sb.toString()
    }

    private fun escapeHtml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")
    }

    private fun escapeMarkdown(text: String): String {
        return text
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("`", "\\`")
            .replace("*", "\\*")
            .replace("_", "\\_")
            .replace("[", "\\[")
            .replace("]", "\\]")
    }

    private fun escapeCsv(text: String): String {
        if (text.isEmpty()) return ""

        val needsQuoting = text.contains(',') ||
                          text.contains('"') ||
                          text.contains('\n') ||
                          text.contains('\r') ||
                          text.startsWith("=") ||
                          text.startsWith("+") ||
                          text.startsWith("-") ||
                          text.startsWith("@")

        val escaped = text.replace("\"", "\"\"")

        return if (needsQuoting) {
            "\"$escaped\""
        } else {
            escaped
        }
    }
}
